### ISSUE TITLE
Set up and style Contact form for v2

### ISSUE THREAD

**Issue by graphitefriction** [opendevise/opendevise.com#4]
We need to implement a new Contact form in v2 of the website.

I used the following two examples to provide a model for the look and feel we want.

Digital visitors contact form (http://digitalvisitor.com/contact/)

**Like:**

- form fields aren't clunky boxes
- labels aren't italicized, they're just regular text
- button text "Send It"

**Ignore:**

- the restricted contact page's layout
- the big block for the project intro; use Viget's "How can we help" field size instead

Viget (https://www.viget.com/contact) has just-as-smooth a contact form as Digital Visitor; but we don't need to include the number of questions they ask.
I also don't want the label text to be italicized.
Their form takes the whole width of the page :+1: 

The draft text for the field labels has been pushed to the v2 branch.

We also need to determine the interaction flow:

- Should the contact section of the website display the section head and a button that would open the contact form or page OR should the contact form already be "open" in the section?
- When they click the "Send it" button, what is displayed next?
- The information should be submitted to the hello email address.

**Comment by mojavelinux** [comment]
I decided to just add a contact section that shows the e-mail address prominently. Since we've had problems receiving e-mail through the web-based proxy in the past, and most people probably prefer to just type their own e-mail, I think this is a reasonable choice in the short run.

One thing we can do to spruce it up is add a subject and body to the e-mail address link. When the user clicks on the link, it would populate these fields in their e-mail client (it even works for gmail).

Here are the details:

https://stackoverflow.com/questions/4782068/can-i-set-subject-content-of-email-with-using-mailto

Here's a handy e-mail link creator:

https://mailto.now.sh/

We just need to decide what we want the subject and body to be, if any.

If and when we do decide to move forward with a form, we'll need to figure out where it belongs on the page. That seems to be the hardest part.

**Comment by mojavelinux** [comment]
migrated to GitLab project
